"""add core opd tables

Revision ID: 201b664e1433
Revises: f0a9cf37fd4a
Create Date: 2026-01-28 23:24:46.166944
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "201b664e1433"
down_revision: Union[str, None] = "f0a9cf37fd4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite ###

    op.create_table(
        "event_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "BOOK",
                "CANCEL",
                "NO_SHOW",
                "EMERGENCY_INSERT",
                "DOCTOR_DELAY",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.Column("slot_id", sa.Integer(), nullable=True),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_logs_id"), "event_logs", ["id"], unique=False)

    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_uid"),
    )
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)

    op.create_table(
        "time_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "start_time", "end_time", name="uq_doctor_slot"),
    )
    op.create_index(op.f("ix_time_slots_id"), "time_slots", ["id"], unique=False)

    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column(
            "booking_source",
            sa.Enum("ONLINE", "WALKIN", "STAFF", "PARTNER", name="bookingsource"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "EMERGENCY",
                "PAID_PRIORITY",
                "FOLLOW_UP",
                "NORMAL",
                name="patientpriority",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "BOOKED",
                "CANCELLED",
                "NO_SHOW",
                "COMPLETED",
                name="appointmentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["time_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appointments_id"), "appointments", ["id"], unique=False)

    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("token_number", sa.Integer(), nullable=False),
        sa.Column("estimated_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ALLOCATED", "MOVED", "CANCELLED", name="tokenstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("appointment_id"),
    )
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=False)

    # ---- SQLite safe ALTER for doctors table ----
    op.add_column("doctors", sa.Column("doctor_code", sa.String(), nullable=True))
    op.add_column("doctors", sa.Column("is_active", sa.Boolean(), nullable=True))

    op.execute("UPDATE doctors SET doctor_code = 'DOC' || id WHERE doctor_code IS NULL;")
    op.execute("UPDATE doctors SET is_active = 1 WHERE is_active IS NULL;")

    # IMPORTANT:
    # do NOT create unique constraint here, SQLite cannot ALTER constraint

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    op.drop_column("doctors", "is_active")
    op.drop_column("doctors", "doctor_code")

    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_table("tokens")

    op.drop_index(op.f("ix_appointments_id"), table_name="appointments")
    op.drop_table("appointments")

    op.drop_index(op.f("ix_time_slots_id"), table_name="time_slots")
    op.drop_table("time_slots")

    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_table("patients")

    op.drop_index(op.f("ix_event_logs_id"), table_name="event_logs")
    op.drop_table("event_logs")
    # ### end Alembic commands ###
